# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VworldReverseGeocoding
                                 A QGIS plugin
 Obtaining address information using the VWorld reverse geocoding API based on the coordinates (longitude, latitude) of a point feature class.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-15
        copyright            : (C) 2025 by KIM SUNGHYUN/Geogreen21 Co.
        email                : shk7773@naver.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VworldReverseGeocoding class from file VworldReverseGeocoding.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .VWorldRevGeocd import VworldReverseGeocoding
    return VworldReverseGeocoding(iface)
